# Basic
title: Sam Lau
subtitle: Follow your passion, enjoy your life
welcome_message: 
description: 一个iOS Developer，Apple重度用户，Unix/Linux脑残粉丝，记录对技术思考和学习的点滴！
creator: <a href="http://samlaudev.cn">@samlaudev</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 

# Navigation buttons in the front page.
nav:
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: sam-lau 
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: samlaudev
    twitter: samlaudev
    mail: samlaudev@gmail.com  

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
